import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [message, setMessage] = useState('');
  const [response, setResponse] = useState('');
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setMessage(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      fetch('api/chatApi', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message }),
      })
        .then((res) => res.json())
        .then((data) => {
          setResponse(data.message);
          setLoading(false);
        });
    } catch (error) {
      setError(!error);
    }
  };

  return (
    <div>
      <Head>
        <title>The Buddha AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.mainTitle}>Ask the Buddha AI</h1>
        <h4 className={styles.subTitle}>
          He speaks every language. He speaks the language of the soul
        </h4>

        <p className={styles.intro}>
          Do you need motivation? - Do you need advice? - Do you have
          existentional doubts?
        </p>
        <form className={styles.form} onSubmit={handleSubmit}>
          <textarea
            value={message}
            onChange={handleChange}
            placeholder="Ask the Buddha"
            className={styles.textarea}
          />

          <button className={styles.button} type="submit">
            Send
          </button>
        </form>
        {loading ? (
          <div className={styles.response}>
            <b>Buddha:</b> I am thinking...
          </div>
        ) : (
          response && (
            <div className={styles.response}>
              <b>Buddha:</b> {response}
            </div>
          )
        )}

        {error && (
          <div className={styles.response}>
            <b>Disciple:</b> Sorry the Budha is restint right now
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        2023 - Coded by Mariano De Simone - All Rights Reserved
      </footer>
    </div>
  );
}
